# Generated by Django 6.0.1 on 2026-01-14 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nazwa tagu')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tagi',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommunityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nazwa wspólnoty')),
                ('description', models.TextField(max_length=500, verbose_name='Krótki opis')),
                ('city', models.CharField(max_length=100, verbose_name='Miasto')),
                ('parish', models.CharField(blank=True, max_length=200, verbose_name='Parafia')),
                ('denomination', models.CharField(blank=True, choices=[('catholic', 'Katolicka'), ('protestant', 'Protestancka'), ('orthodox', 'Prawosławna'), ('evangelical', 'Ewangelikalna'), ('pentecostal', 'Zielonoświątkowa'), ('baptist', 'Baptystyczna'), ('methodist', 'Metodystyczna'), ('charismatic', 'Charyzmatyczna'), ('other', 'Inna')], max_length=50, verbose_name='Denominacja')),
                ('denomination_other', models.CharField(blank=True, help_text='Wypełnij tylko jeśli wybrałeś "Inna"', max_length=100, verbose_name='Inna denominacja (jeśli wybrano "Inna")')),
                ('photo_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='URL zdjęcia głównego')),
                ('logo_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator()], verbose_name='URL logo')),
                ('full_description', models.TextField(blank=True, verbose_name='Pełny opis działalności')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Adres')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email kontaktowy')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Strona WWW')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='Data założenia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia profilu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('is_active', models.BooleanField(default=True, verbose_name='Profil aktywny')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Zweryfikowana')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'community'}, on_delete=django.db.models.deletion.CASCADE, related_name='community_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
                ('tags', models.ManyToManyField(blank=True, related_name='communities', to='communities.tag', verbose_name='Tagi')),
            ],
            options={
                'verbose_name': 'Profil wspólnoty',
                'verbose_name_plural': 'Profile wspólnot',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Imię')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='Nazwisko')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Miasto')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='O mnie')),
                ('photo_url', models.URLField(blank=True, verbose_name='URL zdjęcia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data utworzenia')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ostatnia aktualizacja')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'person'}, on_delete=django.db.models.deletion.CASCADE, related_name='person_profile', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Profil osoby',
                'verbose_name_plural': 'Profile osób',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Członek'), ('leader', 'Lider'), ('service_leader', 'Lider diakonii'), ('admin', 'Administrator')], default='member', max_length=20, verbose_name='Rola')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='Data dołączenia')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktywne członkostwo')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='communities.communityprofile', verbose_name='Wspólnota')),
                ('person', models.ForeignKey(limit_choices_to={'user_type': 'person'}, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL, verbose_name='Osoba')),
            ],
            options={
                'verbose_name': 'Członkostwo',
                'verbose_name_plural': 'Członkostwa',
                'ordering': ['-joined_date'],
                'unique_together': {('person', 'community')},
            },
        ),
    ]
