# Generated by Django 6.0.1 on 2026-03-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_alter_membership_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityprofile',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='communityprofile',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='personprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/', verbose_name='Zdjęcie główne'),
        ),
        migrations.AddField(
            model_name='personprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
