# Generated by Django 6.0.1 on 2026-03-16 20:33

import communities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_remove_communityprofile_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='community_logos/', validators=[communities.validators.validate_image_file], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='communityprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='community_photos/', validators=[communities.validators.validate_image_file], verbose_name='Zdjęcie główne'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[communities.validators.validate_image_file], verbose_name='Avatar'),
        ),
    ]
