# Generated by Django 6.0.1 on 2026-03-17 01:35

import cloudinary.models
import communities.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_communityprofile_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[communities.validators.validate_image_file], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='communityprofile',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[communities.validators.validate_image_file], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='personprofile',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[communities.validators.validate_image_file], verbose_name='image'),
        ),
    ]
