# Generated by Django 6.0.1 on 2026-04-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0005_alter_communityprofile_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Szerokość geograficzna'),
        ),
        migrations.AddField(
            model_name='communityprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Długość geograficzna'),
        ),
    ]
