# Generated by Django 6.0.1 on 2026-04-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_communityprofile_latitude_communityprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Państwo'),
        ),
    ]
