# Generated by Django 6.0.1 on 2026-04-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0007_communityprofile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityprofile',
            name='country',
            field=models.CharField(default='United Kingdom', max_length=50, verbose_name='Państwo'),
            preserve_default=False,
        ),
    ]
