# Generated by Django 6.0.1 on 2026-04-29 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0008_alter_communityprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='personprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, verbose_name='Państwo'),
        ),
    ]
