# Generated by Django 6.0.1 on 2026-04-10 01:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0005_alter_communityprofile_logo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('description', models.TextField(blank=True, verbose_name='Opis')),
                ('date_start', models.DateTimeField(verbose_name='Data rozpoczęcia')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Data zakończenia')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Miejsce')),
                ('is_public', models.BooleanField(default=True, help_text='Publiczne wydarzenia są widoczne dla wszystkich użytkowników portalu.', verbose_name='Publiczne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Utworzone przez')),
            ],
            options={
                'verbose_name': 'Wydarzenie',
                'verbose_name_plural': 'Wydarzenia',
                'ordering': ['date_start'],
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł')),
                ('content', models.TextField(verbose_name='Treść')),
                ('is_public', models.BooleanField(default=True, help_text='Niepubliczne ogłoszenia widoczne tylko dla członków wspólnoty.', verbose_name='Publiczne')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='communities.communityprofile', verbose_name='Wspólnota')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='activities.event', verbose_name='Wydarzenie')),
            ],
            options={
                'verbose_name': 'Ogłoszenie',
                'verbose_name_plural': 'Ogłoszenia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Organizator główny'), ('co_organizer', 'Współorganizator')], default='co_organizer', max_length=20, verbose_name='Rola wspólnoty')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communities.communityprofile', verbose_name='Wspólnota')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.event', verbose_name='Wydarzenie')),
            ],
            options={
                'verbose_name': 'Wspólnota wydarzenia',
                'verbose_name_plural': 'Wspólnoty wydarzenia',
                'unique_together': {('event', 'community')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='communities',
            field=models.ManyToManyField(related_name='events', through='activities.EventCommunity', to='communities.communityprofile', verbose_name='Wspólnoty'),
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner eventu'), ('coordinator', 'Koordynator')], max_length=20, verbose_name='Rola')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='activities.event', verbose_name='Wydarzenie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_roles', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Rola w wydarzeniu',
                'verbose_name_plural': 'Role w wydarzeniu',
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='communities.communityprofile', verbose_name='Obserwowana wspólnota')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='activities.event', verbose_name='Obserwowane wydarzenie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follows', to=settings.AUTH_USER_MODEL, verbose_name='Użytkownik')),
            ],
            options={
                'verbose_name': 'Obserwowanie',
                'verbose_name_plural': 'Obserwowania',
                'constraints': [models.UniqueConstraint(condition=models.Q(('community__isnull', False)), fields=('user', 'community'), name='unique_follow_community'), models.UniqueConstraint(condition=models.Q(('event__isnull', False)), fields=('user', 'event'), name='unique_follow_event')],
            },
        ),
    ]
