# Generated by Django 6.0.1 on 2026-04-23 01:22

import cloudinary.models
import communities.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[communities.validators.validate_image_file], verbose_name='image'),
        ),
    ]
