"""
Django settings for portal_united project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = os.getenv("DEBUG") == "True"

ALLOWED_HOSTS = ['127.0.0.1', 'localhost'] #💡potem zmienic


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Apps
    'communities',
    'accounts',
    # Django-allauth wymaga 'sites' framework
    'django.contrib.sites',
    # Django-allauth - system autoryzacji
    'allauth',
    'allauth.account',
    'allauth.socialaccount',  # Opcjonalnie - dla Google/Facebook login w przyszłości
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Django-allauth wymaga tego middleware
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'portal_united.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #💡sugestia ChatGPT - moze trzeba bedzie zmienic
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portal_united.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': 'localhost',
        'PORT': '5432',
    }
}

# {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

AUTH_USER_MODEL = 'accounts.CustomUser'

# AUTHENTICATION BACKENDS
# Django-allauth potrzebuje własnego backendu obok standardowego
AUTHENTICATION_BACKENDS = [
    # Standardowy backend Django (username/password)
    'django.contrib.auth.backends.ModelBackend',
    
    # Backend allauth - pozwala na logowanie emailem
    'allauth.account.auth_backends.AuthenticationBackend',
]
# ============================================================================
# SITES FRAMEWORK
# Django-allauth wymaga tego - każda instalacja Django może obsługiwać
# wiele stron (sites). My mamy jedną.
SITE_ID = 1

# ============================================================================
# DJANGO-ALLAUTH CONFIGURATION
# Główna konfiguracja zachowania allauth

# --- Rejestracja i logowanie ---

# --- STARE (deprecated) ---
# # Wymagaj adresu email przy rejestracji
# ACCOUNT_EMAIL_REQUIRED = True
# # Metoda autoryzacji: 'username' | 'email' | 'username_email'
# # 'username_email' = użytkownik może zalogować się username LUB emailem
# ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
# # Czy username jest wymagany przy rejestracji? (TAK - potrzebujemy username)
# ACCOUNT_USERNAME_REQUIRED = True


# --DJANGO-ALLAUTH CONFIGURATION - NOWA SKŁADNIA (allauth 0.50+)--
# --- Metody logowania ---
# Użytkownik może logować się username LUB emailem
ACCOUNT_LOGIN_METHODS = ['email', 'username']

# --- Pola rejestracji ---
# Gwiazdka (*) = pole wymagane
# Nasze custom pola (user_type, first_name, community_name) są w CustomSignupForm
ACCOUNT_SIGNUP_FIELDS = [
    'email*',      # Email wymagany
    'username*',   # Username wymagany
    'password1*',  # Hasło wymagane
    'password2*',  # Potwierdzenie hasła wymagane
]
# Email musi być unikalny (dwie osoby nie mogą mieć tego samego emaila)
ACCOUNT_UNIQUE_EMAIL = True

# --- Weryfikacja email ---

# Weryfikacja email: 'mandatory' | 'optional' | 'none'
# 'mandatory' = użytkownik MUSI zweryfikować email żeby się zalogować
# 'optional' = może się zalogować, ale dostanie przypomnienie o weryfikacji
# 'none' = brak weryfikacji
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# Czy automatycznie logować użytkownika po rejestracji?
# False = najpierw musi zweryfikować email, potem się zalogować ❓
# Czy automatycznie logować po weryfikacji email?
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Czy wysłać email powitalny po weryfikacji?
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = '/'

# --- Hasła ---

# Minimalna długość hasła
ACCOUNT_PASSWORD_MIN_LENGTH = 8

# Czy pokazywać hasło podczas wpisywania? (bezpieczniej False)
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = False

# --- Sesje ---

# Czy zapamiętać sesję "zapamiętaj mnie"? => tutaj brak lkiczby dni
ACCOUNT_SESSION_REMEMBER = True

# --- Przekierowania ---

# Gdzie przekierować po zalogowaniu?
LOGIN_REDIRECT_URL = '/'

# Gdzie przekierować po wylogowaniu?
ACCOUNT_LOGOUT_REDIRECT_URL = '/'

# Gdzie przekierować jeśli użytkownik próbuje dostać się do chronionej strony?
LOGIN_URL = '/accounts/login/'

# --- Formularze ---

# Czy podczas rejestracji pytać o imię/nazwisko w standardowym formularzu?
# Ustawimy False bo stworzymy własny formularz ❓
# Nasz custom formularz rejestracji z wyborem typu użytkownika
ACCOUNT_SIGNUP_FORM_CLASS = 'accounts.forms.CustomSignupForm'


# ============================================================================
# EMAIL CONFIGURATION - Wysyłanie emaili weryfikacyjnych

# --- Rozwój (development) - Console Backend ---
# Email będzie "wysyłany" do konsoli/terminala (dla testów lokalnych)
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 3
ACCOUNT_ADAPTER = "allauth.account.adapter.DefaultAccountAdapter"
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# --- Produkcja (production) - Prawdziwe emaile ---
# Odkomentować to gdy będziemy wdrażać na serwer i skonfigurować prawdziwy SMTP

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'  # Dla Gmail
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'twoj-email@gmail.com'  # Twój email
# EMAIL_HOST_PASSWORD = 'twoje-haslo-aplikacji'  # Hasło aplikacji (nie zwykłe hasło!)
# DEFAULT_FROM_EMAIL = 'Portal UNITED <noreply@portalunited.com>'

# Uwaga: Dla Gmail trzeba wygenerować "hasło aplikacji" w ustawieniach konta Google
# (nie używać zwykłego hasła do konta!)

